name: Android CI

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar código del repositorio
      uses: actions/checkout@v4

    - name: Configurar Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # AQUÍ ESTÁ LA SOLUCIÓN: Le decimos que instale la versión 8.7
    - name: Configurar motor de Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: '8.7'

    - name: Generar Wrapper y Compilar APK
      run: |
        gradle wrapper
        ./gradlew assembleDebug --stacktrace

    - name: Subir el APK generado (Búsqueda Flexible)
      uses: actions/upload-artifact@v4
      with:
        name: Optimizer-Pro-APK
        path: '**/build/outputs/apk/debug/*.apk'
